import math
import logging
from typing import List, Dict, Tuple, Optional
from functools import cached_property

import torch

from kirby.data.dataset import DatasetIndex


class RandomFixedWindowSampler(torch.utils.data.Sampler):
    r"""Samples fixed-length windows randomly, given intervals defined in the
    :obj:`interval_dict` parameter. :obj:`interval_dict` is a dictionary where the keys
    are the session ids and the values are lists of tuples representing the
    start and end of the intervals from which to sample. The samples are shuffled, and
    random temporal jitter is applied.


    In one epoch, the number of samples that is generated from a given sampling interval
    is given by:

    .. math::
        N = \left\lfloor\frac{\text{interval_length}}{\text{window_length}}\right\rfloor

    Args:
        interval_dict (Dict[str, List[Tuple[int, int]]]): Sampling intervals for each
            session in the dataset.
        window_length (float): Length of the window to sample.
        generator (Optional[torch.Generator], optional): Generator for shuffling.
            Defaults to None.
    """

    def __init__(
        self,
        *,
        interval_dict: Dict[str, List[Tuple[float, float]]],
        window_length: float,
        generator: Optional[torch.Generator] = None, # default None added
        drop_short: bool = True,
    ):
        self.interval_dict = interval_dict
        self.window_length = window_length
        self.generator = generator
        self.drop_short = drop_short

    @cached_property
    def _estimated_len(self):
        num_samples = 0
        total_short_dropped = 0.0

        for session_name, sampling_intervals in self.interval_dict.items():
            for start, end in sampling_intervals:
                interval_length = end - start
                if interval_length < self.window_length:
                    if self.drop_short:
                        total_short_dropped += interval_length
                        continue
                    else:
                        raise ValueError(
                            f"Interval {(start, end)} ({interval_length:.3f}s) is too short to sample from. "
                            f"Minimum length is {self.window_length}s."
                        )

                # keep this part identical to the original code (estimating sample count)
                # note: may differ slightly from __iter__ logic (especially due to random offset and last sample addition logic)
                # for exact length, compute using same logic as __iter__ or count indices generated by __iter__
                num_samples += math.floor(interval_length / self.window_length)

        if self.drop_short and total_short_dropped > 0:
            logging.warning(
                f"Skipping {total_short_dropped:.2f} seconds of data due to short "
                f"intervals. Estimated remaining samples: {num_samples} "
                f"(approx. {num_samples * self.window_length:.2f} seconds)."
            )

        # note: if num_samples is 0, it is generally better to handle it in __len__ or __iter__ rather than raising an error in _estimated_len

        return num_samples

    def __len__(self):
        length = self._estimated_len
        return length

    def __iter__(self):
        all_indices = [] # list to store all indices

        for session_name, sampling_intervals in self.interval_dict.items():
            for start, end in sampling_intervals:
                interval_length = end - start
                
                if interval_length < self.window_length:
                    #print('session name', session_name, 'interval length', interval_length)
                    if self.drop_short:
                        continue # move to the next interval
                    else:
                        raise ValueError(
                           f"Interval {(start, end)} ({interval_length:.3f}s) is too short to sample from. "
                           f"Minimum length is {self.window_length}s."
                        )

                # --- generate indices for each valid interval ---
                # sample a random offset
                left_offset = (
                    torch.rand(1, generator=self.generator).item() * self.window_length
                )

                # start points generated by arange
                potential_starts = torch.arange(
                    start + left_offset,
                    end, # end is not included
                    self.window_length,
                    dtype=torch.float64,
                )

                # generate (start, end) indices for each start point
                # check that the last window does not exceed the interval end
                indices_ = [
                    DatasetIndex(
                        session_name, t.item(), (t + self.window_length).item()
                    )
                    for t in potential_starts
                    if (t + self.window_length) <= end # this condition is important
                ]

                # add the generated indices to the full list
                if len(indices_) > 0:
                    all_indices.extend(indices_)
                    # compute right_offset based on the end time of the last index
                    right_offset_from_last_sample = end - all_indices[-1].end
                else:
                    # no samples generated by arange
                    right_offset_from_last_sample = interval_length - left_offset # remaining total length


                # --- additional sample logic from the original code ---
                # explanation: if the sum of the discarded front/back fragments (left_offset, right_offset)
                # due to random offset is >= window_length, add one more sample from that space.
                # this may create a slight inconsistency with __len__'s floor calculation, but is an
                # attempt to make the most use of the data.

                if right_offset_from_last_sample + left_offset >= self.window_length:
                    # add sample aligned to the boundary of the longer side (original code logic)
                    if right_offset_from_last_sample > left_offset:
                        # add aligned to interval end
                        all_indices.append(
                            DatasetIndex(session_name, end - self.window_length, end)
                        )
                    else:
                        # add aligned to interval start
                        all_indices.append(
                            DatasetIndex(
                                session_name, start, start + self.window_length
                            )
                        )
                # -----------------------------------------------------------

        # after processing all intervals
        if not all_indices:
             if len(self) > 0:
                 # something is wrong: _estimated_len and __iter__ logic are inconsistent
                 logging.error(f"Sampler estimated length {len(self)}, but generated 0 indices. Check logic.")
                 return # return empty iterator
             else:
                 # estimated length was 0 and no indices exist: normal termination
                 return # return empty iterator

        print('length of all indices', len(all_indices))
        # --- shuffle once after collecting all indices ---
        indices_to_yield = torch.randperm(len(all_indices), generator=self.generator)
        for i in indices_to_yield:
            yield all_indices[i]

'''
class RandomFixedWindowSampler(torch.utils.data.Sampler):
    r"""Samples fixed-length windows randomly, given intervals defined in the
    :obj:`interval_dict` parameter. :obj:`interval_dict` is a dictionary where the keys
    are the session ids and the values are lists of tuples representing the
    start and end of the intervals from which to sample. The samples are shuffled, and
    random temporal jitter is applied.


    In one epoch, the number of samples that is generated from a given sampling interval
    is given by:

    .. math::
        N = \left\lfloor\frac{\text{interval_length}}{\text{window_length}}\right\rfloor

    Args:
        interval_dict (Dict[str, List[Tuple[int, int]]]): Sampling intervals for each
            session in the dataset.
        window_length (float): Length of the window to sample.
        generator (Optional[torch.Generator], optional): Generator for shuffling.
            Defaults to None.
    """

    def __init__(
        self,
        *,
        interval_dict: Dict[str, List[Tuple[float, float]]],
        window_length: float,
        generator: Optional[torch.Generator],
        drop_short: bool = True,
    ):
        self.interval_dict = interval_dict
        self.window_length = window_length
        self.generator = generator
        self.drop_short = drop_short

    @cached_property
    def _estimated_len(self):
        num_samples = 0
        total_short_dropped = 0.0

        for session_name, sampling_intervals in self.interval_dict.items():
            for start, end in sampling_intervals:
                interval_length = end - start
                if interval_length >= 0.03:
                    if interval_length < self.window_length:
                        if self.drop_short:
                            total_short_dropped += interval_length
                            continue
                        else:
                            raise ValueError(
                                f"Interval {(start, end)} is too short to sample from. "
                                f"Minimum length is {self.window_length}."
                            )

                    # print('interval length', interval_length)
                    # print('window length', self.window_length)

                    num_samples += math.floor(interval_length / self.window_length)
                else:
                    print('interval length', interval_length)

                    pass

        if self.drop_short and total_short_dropped > 0:
            logging.warning(
                f"Skipping {total_short_dropped} seconds of data due to short "
                f"intervals. Remaining: {num_samples * self.window_length} seconds."
            )
            if num_samples == 0:
                raise ValueError("All intervals are too short to sample from.")
        return num_samples

    def __len__(self):
        return self._estimated_len

    def __iter__(self):
        if len(self) == 0.0:
            raise ValueError("All intervals are too short to sample from.")

        indices = []
        for session_name, sampling_intervals in self.interval_dict.items():
            for start, end in sampling_intervals:
                interval_length = end - start
                if interval_length >= 0.03:
                    if interval_length < self.window_length:
                        if self.drop_short:
                            continue
                        else:
                            raise ValueError(
                                f"Interval {(start, end)} is too short to sample from. "
                                f"Minimum length is {self.window_length}."
                            )

                    # sample a random offset
                    left_offset = (
                        torch.rand(1, generator=self.generator).item() * self.window_length
                    )

                    indices_ = [
                        DatasetIndex(
                            session_name, t.item(), (t + self.window_length).item()
                        )
                        for t in torch.arange(
                            start + left_offset,
                            end,
                            self.window_length,
                            dtype=torch.float64,
                        )
                        if t + self.window_length <= end
                    ]

                    if len(indices_) > 0:
                        indices.extend(indices_)
                        right_offset = end - indices[-1].end
                    else:
                        right_offset = end - start - left_offset

                    # if there is one sample worth of data, add it
                    # this ensures that the number of samples is always consistent
                    if right_offset + left_offset >= self.window_length:
                        if right_offset > left_offset:
                            indices.append(
                                DatasetIndex(session_name, end - self.window_length, end)
                            )
                        else:
                            indices.append(
                                DatasetIndex(
                                    session_name, start, start + self.window_length
                                )
                            )
                else:
                    pass
            # shuffle
            for idx in torch.randperm(len(indices), generator=self.generator):
                yield indices[idx]
    def __getitem__(self, index):
        return self._indices[index]
'''

class SequentialFixedWindowSampler(torch.utils.data.Sampler):
    r"""Samples fixed-length windows sequentially, always in the same order. The
    sampling intervals are defined in the :obj:`interval_dict` parameter.
    :obj:`interval_dict` is a dictionary where the keys are the session ids and the
    values are lists of tuples representing the start and end of the intervals
    from which to sample.

    If the length of a sequence is not evenly divisible by the step, the last
    window will be added with an overlap with the previous window. This is to ensure
    that the entire sequence is covered.

    Args:
        interval_dict (Dict[str, List[Tuple[int, int]]]): Sampling intervals for each
            session in the dataset.
        window_length (float): Length of the window to sample.
        step (Optional[float], optional): Step size between windows. If None, it
            defaults to `window_length`. Defaults to None.
    """

    def __init__(
        self,
        *,
        interval_dict: Dict[str, List[Tuple[float, float]]],
        window_length: float,
        step: Optional[float] = None,
        drop_short=False,
    ):
        self.interval_dict = interval_dict
        self.window_length = window_length
        self.step = step or window_length
        self.drop_short = drop_short

        assert self.step > 0, "Step must be greater than 0."
        assert self.step <= self.window_length, "Step must be less than window length."

    # we cache the indices since they are deterministic
    @cached_property
    def _indices(self) -> List[DatasetIndex]:
        indices = []
        total_short_dropped = 0.0

        for session_name, sampling_intervals in self.interval_dict.items():
            for start, end in sampling_intervals:
                interval_length = end - start
                if interval_length >= 0.033:
                    if interval_length < self.window_length:
                        if self.drop_short:
                            total_short_dropped += interval_length
                            continue
                        else:
                            raise ValueError(
                                f"Interval {(start, end)} is too short to sample from. "
                                f"Minimum length is {self.window_length}."
                            )

                    indices_ = [
                        DatasetIndex(
                            session_name, t.item(), (t + self.window_length).item()
                        )
                        for t in torch.arange(start, end, self.step, dtype=torch.float64)
                        if t + self.window_length <= end
                    ]
                    # print(f"{session_name}: {len(indices_)} samples")

                    indices.extend(indices_)

                    # we need to make sure that the entire interval is covered
                    if indices_[-1].end < end:
                        indices.append(
                            DatasetIndex(session_name, end - self.window_length, end)
                        )

            if self.drop_short and total_short_dropped > 0:
                num_samples = len(indices)
                logging.warning(
                    f"Skipping {total_short_dropped} seconds of data due to short "
                    f"intervals. Remaining: {num_samples * self.window_length} seconds."
                )
                if num_samples == 0:
                    raise ValueError("All intervals are too short to sample from.")

        return indices

    def __len__(self):
        return len(self._indices)

    def __iter__(self):
        yield from self._indices

    def __getitem__(self, index):
        return self._indices[index]


class TrialSampler(torch.utils.data.Sampler):
    r"""Randomly samples a single trial interval from the given intervals.

    Args:
        interval_dict (Dict[str, List[Tuple[int, int]]]): Sampling intervals for each
            session in the dataset.
        generator (Optional[torch.Generator], optional): Generator for shuffling.
            Defaults to None.
    """

    def __init__(
        self,
        *,
        interval_dict: Dict[str, List[Tuple[float, float]]],
        generator: Optional[torch.Generator] = None,
        shuffle: bool = True,
    ):
        self.interval_dict = interval_dict
        self.generator = generator
        self.shuffle = shuffle

    def __len__(self):
        return sum(len(intervals) for intervals in self.interval_dict.values())

    def __iter__(self):
        # Flatten the intervals from all sessions into a single list
        all_intervals = [
            (session_id, start, end)
            for session_id, intervals in self.interval_dict.items()
            for start, end in intervals
        ]

        indices = [
            DatasetIndex(session_id, start, end)
            for session_id, start, end in all_intervals
        ]

        if self.shuffle:
            # Yield a single DatasetIndex representing the selected interval
            for idx in torch.randperm(len(indices), generator=self.generator):
                yield indices[idx]
        else:
            yield from indices


class DistributedSamplerWrapper(torch.utils.data.Sampler):
    r"""Wraps a sampler to be used in a distributed setting. This sampler will
    only return indices that are assigned to the current process based on the
    rank and num_replicas.
    Args:
        sampler (torch.utils.data.Sampler): The original sampler to wrap.
        num_replicas (int): Number of processes participating in the distributed
            training.
        rank (int): Rank of the current process.
    Example:
        >>> sampler = SequentialFixedWindowSampler(interval_dict, window_length=10)
        >>> dist_sampler = DistributedSamplerWrapper(sampler)
        >>> loader = torch.utils.data.DataLoader(dataset, sampler=dist_sampler)
        # Before starting the training loop, set the rank and num_replicas attributes:
        >>> dist_sampler.set_params(trainer.world_size, trainer.global_rank)
        # Now use it
    """

    def __init__(self, sampler, num_replicas=None, rank=None):
        self.sampler = sampler
        self.num_replicas = num_replicas
        self.rank = rank

    def set_params(self, num_replicas, rank):
        logging.info(
            f"Setting distributed sampler params: "
            f"num_replicas={num_replicas}, rank={rank}"
        )
        self.num_replicas = num_replicas
        self.rank = rank

    def _check_params(self):
        return (self.num_replicas is not None) and (self.rank is not None)

    def rank_len(self):
        r"""Returns the number of samples assigned to the current process."""
        total_len = len(self.sampler)
        evenly_split = total_len // self.num_replicas
        extra = int((total_len % self.num_replicas) < self.rank)
        return evenly_split + extra

    def __len__(self):
        r"""Returns the number of samples assigned to the current process if
        the rank and num_replicas are set. Otherwise, returns the total number
        of samples in the original sampler.
        """
        if not self._check_params():
            return len(self.sampler)
        else:
            return self.rank_len()

    def __iter__(self):
        assert (
            self._check_params()
        ), "Rank and num_replicas must be set before using the distributed sampler."
        indices = list(self.sampler)
        indices = indices[self.rank : len(indices) : self.num_replicas]
        return iter(indices)